### ISSUE TITLE
The shapes.html has several bad links

### ISSUE THREAD

**Issue by juggledad** [raspberrypilearning/shapes#1]
top of page 'Index' causes a download result of: 400: Invalid request

top of page has shows c:\users\laura\documents\github\shapes\shapes.py 

modules -> 'Random' gets Error: Cannot load file - it is trying to load 'random.html' which becomes https://raw.githubusercontent.com/raspberrypilearning/shapes/master/random.html which doesn't exist

class Oval(Shapes) -> builtins.object - goes nowhere
class Rectangle(Shapes) -> builtins.object - goes nowhere
class Shapes(builtins.object) - goes nowhere
class Triangle(Shapes) -> builtins.object - goes nowhere

Note: there are 27 places in the code where - having define anchors) you reference them using 'xxxxx.html#name' syntax instead of just '#name'. For example on line 154 of the raw source you have:
<font color="#000000" face="helvetica, arial"><a name="Shape">class <strong>Shape</strong></a>(<a href="builtins.html#object">builtins.object</a>)</font></td></tr>
so you have defined the anchor as 'Shape' but on line 215 you have
	Methods inherited from <a href="shapes.html#Shape">Shape</a>:<br>
which should be code as:
	Methods inherited from <a href="#Shape">Shape</a>:<br>

Here is the html with all the 'xxxxx.html#name' occurrences changed to '#name'

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><title>Python: module shapes</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#f0f0f8">

<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
	<tr bgcolor="#7799ee">
		<td valign=bottom> <br>
			<font color="#ffffff" face="helvetica, arial"> <br><big><big><strong>shapes</strong></big></big></font>
			</td
>
		<td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial"><a href=".">index</a><br><a href="file:c%3A%5Cusers%5Claura%5Cdocuments%5Cgithub%5Cshapes%5Cshapes.py">c:\users\laura\documents\github\shapes\shapes.py</a></font></td></tr></table>
    <p><tt># This code requires Python 3 and tkinter (which is usually installed by default)<br>
# This code will NOT work on trinket.io as the tkinter module is not supported<br>
# Raspberry Pi Foundation 2017<br>
# CC-BY-SA 4.0</tt></p>
<p>
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="section">
<tr bgcolor="#aa55cc">
<td colspan=3 valign=bottom> <br>
<font color="#ffffff" face="helvetica, arial"><big><strong>Modules</strong></big></font></td></tr>

<tr><td bgcolor="#aa55cc"><tt>      </tt></td><td> </td>
<td width="100%"><table width="100%" summary="list"><tr><td width="25%" valign=top><a href="random.html">random</a><br>
</td><td width="25%" valign=top></td><td width="25%" valign=top></td><td width="25%" valign=top></td></tr></table></td></tr></table><p>
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="section">
<tr bgcolor="#ee77aa">
<td colspan=3 valign=bottom> <br>
<font color="#ffffff" face="helvetica, arial"><big><strong>Classes</strong></big></font></td></tr>

<tr><td bgcolor="#ee77aa"><tt>      </tt></td><td> </td>
<td width="100%"><dl>
<dt><font face="helvetica, arial"><a href="#object">builtins.object</a>
</font></dt><dd>
<dl>
<dt><font face="helvetica, arial"><a href="#Shape">Shape</a>
</font></dt><dd>
<dl>
<dt><font face="helvetica, arial"><a href="#Oval">Oval</a>
</font></dt><dt><font face="helvetica, arial"><a href="#Rectangle">Rectangle</a>
</font></dt><dt><font face="helvetica, arial"><a href="#Triangle">Triangle</a>
</font></dt></dl>
</dd>
</dl>
</dd>

</dl>
 <p>
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="section">
<tr bgcolor="#ffc8d8">
<td colspan=3 valign=bottom> <br>
<font color="#000000" face="helvetica, arial"><a name="Oval">class <strong>Oval</strong></a>(<a href="#Shape">Shape</a>)</font></td></tr>

<tr><td bgcolor="#ffc8d8"><tt>   </tt></td><td> </td>
<td width="100%"><dl><dt>Method resolution order:</dt>
<dd><a href="#Oval">Oval</a></dd>
<dd><a href="#Shape">Shape</a></dd>
<dd><a href="#object">builtins.object</a></dd>
</dl>
<hr>
Methods defined here:<br>
<dl><dt><a name="Oval-draw"><strong>draw</strong></a>(self)</dt><dd><tt>Draws an oval on the canvas. The properties of the oval<br>
can be set using the getter and setter methods in <a href="#Shape">Shape</a></tt></dd></dl>

<hr>
Methods inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><a name="Oval-__init__"><strong>__init__</strong></a>(self, width=50, height=50, x=None, y=None, color='black')</dt><dd><tt>Creates a generic 'shape' which contains properties common to all<br>
shapes such as height, width, x y coordinates and colour.</tt></dd></dl>

<dl><dt><a name="Oval-get_color"><strong>get_color</strong></a>(self)</dt><dd><tt>Returns the colour of the shape</tt></dd></dl>

<dl><dt><a name="Oval-randomise"><strong>randomise</strong></a>(self, width=20, height=200)</dt><dd><tt>Randomly generates width, height, position and colour for a shape</tt></dd></dl>

<dl><dt><a name="Oval-set_color"><strong>set_color</strong></a>(self, color)</dt><dd><tt>Sets the colour of the shape</tt></dd></dl>

<dl><dt><a name="Oval-set_height"><strong>set_height</strong></a>(self, height)</dt><dd><tt>Sets the height of the shape</tt></dd></dl>

<dl><dt><a name="Oval-set_width"><strong>set_width</strong></a>(self, width)</dt><dd><tt>Sets the width of the shape</tt></dd></dl>

<dl><dt><a name="Oval-set_x"><strong>set_x</strong></a>(self, x)</dt><dd><tt>Sets the x position of the shape</tt></dd></dl>

<dl><dt><a name="Oval-set_y"><strong>set_y</strong></a>(self, y)</dt><dd><tt>Sets the y position of the shape</tt></dd></dl>

<hr>
Data descriptors inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><strong>__dict__</strong></dt>
<dd><tt>dictionary for instance variables (if defined)</tt></dd>
</dl>
<dl><dt><strong>__weakref__</strong></dt>
<dd><tt>list of weak references to the object (if defined)</tt></dd>
</dl>
<hr>
Data and other attributes inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><strong>paper</strong> = &lt;shapes.Paper object .&gt;</dl>

</td></tr></table> <p>
<p>
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="section">
<tr bgcolor="#ffc8d8">
<td colspan=3 valign=bottom> <br>
<font color="#000000" face="helvetica, arial"><a name="Rectangle">class <strong>Rectangle</strong></a>(<a href="#Shape">Shape</a>)</font></td></tr>

<tr bgcolor="#ffc8d8"><td rowspan=2><tt>   </tt></td>
<td colspan=2><tt># <a href="#Rectangle">Rectangle</a> class is a subclass of <a href="#Shape">Shape</a><br> </tt></td></tr>
<tr><td> </td>
<td width="100%"><dl><dt>Method resolution order:</dt>
<dd><a href="#Rectangle">Rectangle</a></dd>
<dd><a href="#Shape">Shape</a></dd>
<dd><a href="#object">builtins.object</a></dd>
</dl>
<hr>
Methods defined here:<br>
<dl><dt><a name="Rectangle-draw"><strong>draw</strong></a>(self)</dt><dd><tt>Draws a rectangle on the canvas. The properties of the rectangle<br>
can be set using the getter and setter methods in <a href="#Shape">Shape</a></tt></dd></dl>

<hr>
Methods inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><a name="Rectangle-__init__"><strong>__init__</strong></a>(self, width=50, height=50, x=None, y=None, color='black')</dt><dd><tt>Creates a generic 'shape' which contains properties common to all<br>
shapes such as height, width, x y coordinates and colour.</tt></dd></dl>

<dl><dt><a name="Rectangle-get_color"><strong>get_color</strong></a>(self)</dt><dd><tt>Returns the colour of the shape</tt></dd></dl>

<dl><dt><a name="Rectangle-randomise"><strong>randomise</strong></a>(self, width=20, height=200)</dt><dd><tt>Randomly generates width, height, position and colour for a shape</tt></dd></dl>

<dl><dt><a name="Rectangle-set_color"><strong>set_color</strong></a>(self, color)</dt><dd><tt>Sets the colour of the shape</tt></dd></dl>

<dl><dt><a name="Rectangle-set_height"><strong>set_height</strong></a>(self, height)</dt><dd><tt>Sets the height of the shape</tt></dd></dl>

<dl><dt><a name="Rectangle-set_width"><strong>set_width</strong></a>(self, width)</dt><dd><tt>Sets the width of the shape</tt></dd></dl>

<dl><dt><a name="Rectangle-set_x"><strong>set_x</strong></a>(self, x)</dt><dd><tt>Sets the x position of the shape</tt></dd></dl>

<dl><dt><a name="Rectangle-set_y"><strong>set_y</strong></a>(self, y)</dt><dd><tt>Sets the y position of the shape</tt></dd></dl>

<hr>
Data descriptors inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><strong>__dict__</strong></dt>
<dd><tt>dictionary for instance variables (if defined)</tt></dd>
</dl>
<dl><dt><strong>__weakref__</strong></dt>
<dd><tt>list of weak references to the object (if defined)</tt></dd>
</dl>
<hr>
Data and other attributes inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><strong>paper</strong> = &lt;shapes.Paper object .&gt;</dl>

</td></tr></table> <p>

<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="section">
<tr bgcolor="#ffc8d8">
<td colspan=3 valign=bottom> <br>
<font color="#000000" face="helvetica, arial"><a name="Shape">class <strong>Shape</strong></a>(<a href="#object">builtins.object</a>)</font></td></tr>

<tr><td bgcolor="#ffc8d8"><tt>   </tt></td><td> </td>
<td width="100%">Methods defined here:<br>
<dl><dt><a name="Shape-__init__"><strong>__init__</strong></a>(self, width=50, height=50, x=None, y=None, color='black')</dt><dd><tt>Creates a generic 'shape' which contains properties common to all<br>
shapes such as height, width, x y coordinates and colour.</tt></dd></dl>

<dl><dt><a name="Shape-get_color"><strong>get_color</strong></a>(self)</dt><dd><tt>Returns the colour of the shape</tt></dd></dl>

<dl><dt><a name="Shape-randomise"><strong>randomise</strong></a>(self, width=20, height=200)</dt><dd><tt>Randomly generates width, height, position and colour for a shape</tt></dd></dl>

<dl><dt><a name="Shape-set_color"><strong>set_color</strong></a>(self, color)</dt><dd><tt>Sets the colour of the shape</tt></dd></dl>

<dl><dt><a name="Shape-set_height"><strong>set_height</strong></a>(self, height)</dt><dd><tt>Sets the height of the shape</tt></dd></dl>

<dl><dt><a name="Shape-set_width"><strong>set_width</strong></a>(self, width)</dt><dd><tt>Sets the width of the shape</tt></dd></dl>

<dl><dt><a name="Shape-set_x"><strong>set_x</strong></a>(self, x)</dt><dd><tt>Sets the x position of the shape</tt></dd></dl>

<dl><dt><a name="Shape-set_y"><strong>set_y</strong></a>(self, y)</dt><dd><tt>Sets the y position of the shape</tt></dd></dl>

<hr>
Data descriptors defined here:<br>
<dl><dt><strong>__dict__</strong></dt>
<dd><tt>dictionary for instance variables (if defined)</tt></dd>
</dl>
<dl><dt><strong>__weakref__</strong></dt>
<dd><tt>list of weak references to the object (if defined)</tt></dd>
</dl>
<hr>
Data and other attributes defined here:<br>
<dl><dt><strong>paper</strong> = &lt;shapes.Paper object .&gt;</dl>

</td></tr></table> <p>
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="section">
<tr bgcolor="#ffc8d8">
<td colspan=3 valign=bottom> <br>
<font color="#000000" face="helvetica, arial"><a name="Triangle">class <strong>Triangle</strong></a>(<a href="#Shape">Shape</a>)</font></td></tr>

<tr><td bgcolor="#ffc8d8"><tt>   </tt></td><td> </td>
<td width="100%"><dl><dt>Method resolution order:</dt>
<dd><a href="#Triangle">Triangle</a></dd>
<dd><a href="#Shape">Shape</a></dd>
<dd><a href="#object">builtins.object</a></dd>
</dl>
<hr>
Methods defined here:<br>
<dl><dt><a name="Triangle-__init__"><strong>__init__</strong></a>(self, x1=0, y1=0, x2=20, y2=0, x3=20, y3=20, color='black')</dt><dd><tt>Overrides the <a href="#Shape">Shape</a> constructor because triangles require three<br>
coordinate points to be drawn, unlike rectangles and ovals.</tt></dd></dl>

<dl><dt><a name="Triangle-draw"><strong>draw</strong></a>(self)</dt><dd><tt>Draws a triangle on the canvas. The properties of the triangle<br>
can be set using the getter and setter methods in <a href="#Shape">Shape</a></tt></dd></dl>

<dl><dt><a name="Triangle-randomise"><strong>randomise</strong></a>(self)</dt><dd><tt>Randomly chooses the location of all 3 triangle points as well<br>
as the colour of the triangle</tt></dd></dl>

<dl><dt><a name="Triangle-set_height"><strong>set_height</strong></a>(self, height)</dt><dd><tt>Overrides the setter method for height</tt></dd></dl>

<dl><dt><a name="Triangle-set_width"><strong>set_width</strong></a>(self, width)</dt><dd><tt>Overrides the setter method for width</tt></dd></dl>

<hr>
Methods inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><a name="Triangle-get_color"><strong>get_color</strong></a>(self)</dt><dd><tt>Returns the colour of the shape</tt></dd></dl>

<dl><dt><a name="Triangle-set_color"><strong>set_color</strong></a>(self, color)</dt><dd><tt>Sets the colour of the shape</tt></dd></dl>

<dl><dt><a name="Triangle-set_x"><strong>set_x</strong></a>(self, x)</dt><dd><tt>Sets the x position of the shape</tt></dd></dl>

<dl><dt><a name="Triangle-set_y"><strong>set_y</strong></a>(self, y)</dt><dd><tt>Sets the y position of the shape</tt></dd></dl>

<hr>
Data descriptors inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><strong>__dict__</strong></dt>
<dd><tt>dictionary for instance variables (if defined)</tt></dd>
</dl>
<dl><dt><strong>__weakref__</strong></dt>
<dd><tt>list of weak references to the object (if defined)</tt></dd>
</dl>
<hr>
Data and other attributes inherited from <a href="#Shape">Shape</a>:<br>
<dl><dt><strong>paper</strong> = &lt;shapes.Paper object .&gt;</dl>

</td></tr></table></td></tr></table><p>
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="section">
<tr bgcolor="#55aa55">
<td colspan=3 valign=bottom> <br>
<font color="#ffffff" face="helvetica, arial"><big><strong>Data</strong></big></font></td></tr>

<tr><td bgcolor="#55aa55"><tt>      </tt></td><td> </td>
<td width="100%"><strong>BOTH</strong> = 'both'</td></tr></table>
</body></html>

**Comment by martinohanlon** [comment]
I believe this issue has been resolved. so closing.
